In [1]:
import numpy as np
import pandas as pd

In [2]:
print("-----------NUMPY-------------")
marks = np.array([85,72,90,68,95,78])
print("Orginal Arrays:")
print(marks)
print("\n--------Numpy Indexing--------")
print("First mark:",marks[0])
print("Third mark:",marks[2])
print("Last element:",marks[-1])

-----------NUMPY-------------
Orginal Arrays:
[85 72 90 68 95 78]

--------Numpy Indexing--------
First mark: 85
Third mark: 90
Last element: 78


In [4]:
print("\n--------Numpy Slicing-----")
print("First three marks:",marks[0:3])
print("Marks from index 2 to 4:",marks[2:5])
print("Every second marks:",marks[::2])
print("Reverse:",marks[::-1])
      


--------Numpy Slicing-----
First three marks: [85 72 90]
Marks from index 2 to 4: [90 68 95]
Every second marks: [85 90 95]
Reverse: [78 95 68 90 72 85]


In [5]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
C = A + B
print("Matrix A:")
print(A)
print("Matrix B:")
print(B)
print("Addition:")
print(C)

Matrix A:
[[1 2]
 [3 4]]
Matrix B:
[[5 6]
 [7 8]]
Addition:
[[ 6  8]
 [10 12]]


In [6]:
df=pd.DataFrame({
    "Name":["Ankitha","Abhishruti","Gunashree","Yogesh","Shilpa"],
    "Python":[90,95,94,85,80],
    "Maths":[95,96,92,90,91],
    "AI":[96,90,89,75,70],
})
print("Orginal Dataframe:")
print(df)

Orginal Dataframe:
         Name  Python  Maths  AI
0     Ankitha      90     95  96
1  Abhishruti      95     96  90
2   Gunashree      94     92  89
3      Yogesh      85     90  75
4      Shilpa      80     91  70


In [9]:
a=np.array([25000,32000,28000,35000,40000,38000])
print("Sum:",np.sum(a))
print("Average:",np.mean(a))
print("Maximum:",np.max(a))
print("Minimum:",np.min(a))
print("Sales from third month:",a[2:])
print("Every second month sales:",a[0::2])


Sum: 198000
Average: 33000.0
Maximum: 40000
Minimum: 25000
Sales from third month: [28000 35000 40000 38000]
Every second month sales: [25000 28000 40000]


In [10]:
data = {
    "Name": ["Rahul", "Priya", "Amit", "Sneha"],
    "Marks": [75, 90, 65, 95]
}
df = pd.DataFrame(data)
result = df[df["Marks"] > 80]
print(result)


    Name  Marks
1  Priya     90
3  Sneha     95


In [11]:
data = {
    "Name": ["John", "Alice", "Bob", "David"],
    "Marks": [85, 90, 75, 88]
}
df = pd.DataFrame(data)
average = df["Marks"].mean()
print("Average marks:", average)


Average marks: 84.5
